export declare const primary = "#6200ee";
export declare const on_primary: string;
export declare const accent = "#018786";
export declare const secondary = "#018786";
export declare const on_secondary: string;
export declare const background = "#fff";
export declare const surface = "#fff";
export declare const on_surface: string;
export declare const error = "#b00020";
export declare const on_error: string;
export declare const text_colors: Record<string, Record<string, string>>;
export declare const text_emphasis: {
    high: number;
    medium: number;
    disabled: number;
};
export declare const property_values: {
    primary: string;
    secondary: string;
    background: string;
    surface: string;
    error: string;
    on_primary: string;
    on_secondary: string;
    on_surface: string;
    on_error: string;
    text_primary_on_background: string;
    text_secondary_on_background: string;
    text_hint_on_background: string;
    text_disabled_on_background: string;
    text_icon_on_background: string;
    text_primary_on_light: string;
    text_secondary_on_light: string;
    text_hint_on_light: string;
    text_disabled_on_light: string;
    text_icon_on_light: string;
    text_primary_on_dark: string;
    text_secondary_on_dark: string;
    text_hint_on_dark: string;
    text_disabled_on_dark: string;
    text_icon_on_dark: string;
};
